### ISSUE TITLE
Barcode scanner issue

### ISSUE THREAD

**Issue by fbcalibrary** [Librarika/Issues#114]
When trying to circulate items using the barcode scanner, there seems to be an issue with how quickly the information is processed in Librarika.  If I type the accession number manually, it takes a couple of seconds to process and find the item which it then pulls up just fine.  But when using the barcode scanner, I get the error message "Accession no is required!" Thanks in advance for any help you can provide.  Let me know if screenshots would be helpful or if you have any other questions.

**Comment by foolhandy** [comment]
I have, I think, the same problem with the scanner giving that error message but a manual data input being fine. For me though the book pop-up I get on manual input appears in the top left corner of the browser (see attachment) which can't be clicked on because it's 'behind' the data input pop-up. I've tried in Chrome & Firefox and had the same problem. 
![libraryscanner](https://cloud.githubusercontent.com/assets/9577088/8035447/ba2edb18-0de8-11e5-869a-2d47942487d5.jpg)

**Comment by rayhan** [comment]
Thanks for reporting, will look into the issue.

On Mon, Jun 8, 2015 at 7:15 PM, foolhandy <notifications@github.com> wrote:

> I have, I think, the same problem with the scanner giving that error
> message but a manual data input being fine. For me though the book pop-up I
> get on manual input appears in the top left corner of the browser (see
> attachment) which can't be clicked on because it's 'behind' the data input
> pop-up. I've tried in Chrome & Firefox and had the same problem.
> [image: libraryscanner]
> <https://cloud.githubusercontent.com/assets/9577088/8035447/ba2edb18-0de8-11e5-869a-2d47942487d5.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Librarika/Issues/issues/114#issuecomment-109991724>.
>



-- 
Rayhan

**Comment by foolhandy** [comment]
Thanks for looking into this for me. :-) I've just noticed on re-reading my post that I said 'manual' rather than 'bar code' - I've updated the post with the correction in italics.

To clarify:
When I enter the accession number with the keyboard (manually) the book title pop-up appears in the front window under the Accession No. box so it can be clicked on.
I get what you see above when using the bar code scanner.
If I try and click on the book title pop-up that's in the top left corner and 'behind' the Quick Check-in pop-up I just go back to the Dashboard and no changes are made.

Sorry if I've been confusing and again, thank you!

We've very excited about using Librarika in our school!

**Comment by stagetech** [comment]
Has this issue been solved yet? I am having the same exact issue.

**Comment by rayhan** [comment]
Fixed.

**Comment by stagetech** [comment]
Hello! The same issue is occurring on the “Quick Return” page. Can you please fix that also?

**Comment by rayhan** [comment]
This has been fixed now for scanner with auto form submission, check this now.
