### ISSUE TITLE
Accessibility and Speed

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#197]
Hi,

Could a few changes be made to enable people who cannot use a mouse to use the site? This would also help other users do things more quickly in many occasions. For example the ability to press enter to submit the Smart Add barcode input dialogue, and keyboard shortcuts (Enter / Esc) to view book or close popup after adding a book with Smart Add.

**Comment by rayhan** [comment]
ESC key is already configured, it should be working to close popup. 

Regarding Enter key, we disabled auto submission by enter key in order to fix an issue with barcode scanner. Some barcode scanner auto submit the form right after scanning causing issue on different libraries who doesn't know how to disable the enter key on their scanner itself. Will need more thought on this and let you know.

**Comment by shiv379** [comment]
Hmm I see your point. Maybe set it so users can tab to the "View Book" field and then submit? Better yet add some kind of checkbox (in preferences?) that enables / disables enter key submission, so users who want to use submission from the scanner can do so? I actually found it quicker that way and was disappointed when it stopped working! Thanks :)

**Comment by rayhan** [comment]
No worries, will add some logic to detect manual entry and barcode entry based on the input behaviours.

**Comment by rayhan** [comment]
Improved the script, please refresh your browser cache. 

Normal enter key submission will work now based on the speed of input characters.
