### ISSUE TITLE
Missing fields on Export All Copies report

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#203]
Hi,

The following fields seem to be missing from the Export All Copies report:
-Series
-Price
-Branch
-Location
-Remarks
-Included Materials
-Purchase

**Comment by foolhandy** [comment]
Has this enhancement been added yet? We particularly need to find a way of seeing all remarks left on the returned books.

**Comment by rayhan** [comment]
@foolhandy you can get all remarks form the Reports -> Circulations -> Advance report. There is a check box "Has note?", please select the checkbox and you can see all notes on circulations.

**Comment by rayhan** [comment]
All the fields added when exporting copies except price and purchase.

**Comment by foolhandy** [comment]
Thanks for the response! 👍 

However... The Reports -> Circulations -> Advance report form requires a User Number. Is there a way of typing a wildcard in that box so that ALL users/books with remarks are shown?

For the downloaded report there's no column for the remarks left about returned books (see attached file - with books removed but column titles left untouched.
[catalog-copies.csv.zip](https://github.com/Librarika/Issues/files/240161/catalog-copies.csv.zip)
)

**Comment by rayhan** [comment]
@foolhandy I believe there is a misunderstanding, the Advance report doesn't require user number or any other filters, those are optional. You just select specific date range and check "**Has note?**" box. This way it will generate reports with remarks. You can then export the generated report by clicking on "Export CSV" button.

**Comment by panchtatvam** [comment]
Any update on exporting remarks on all copies ?
