### ISSUE TITLE
Smart Add unable to find (most of the) books in Analytics/Software

### ISSUE THREAD

**Issue by sagarjoshi3183** [Librarika/Issues#245]
Hi Rayhan,

Thanks for maintaining the awesome platform. 

However, there's one small thing that would be great to be resolved if possible. We have a lot of software and analytics books in our library. But the smart add function can't seem to be able to find these ISBN online. I believe other subject textbooks might be facing the same problem because textbooks are not always available on all databases from which the smart add function might be sourcing the information. All these books with these ISBN's are however available on Amazon India. Could you please look into it whenever possible.

Thanks

**Comment by sagarjoshi3183** [comment]
Hi! Can anything be done about this please?

**Comment by rayhan** [comment]
We added two more big book sources in our back-end on experimental basis, it will get more items than before. 

However in order to use Amazon India, we need an Indian address to signup for API permissions. Since, We are not located in India, its not possible get a valid Indian address. Any help in this regard might be helpful. I'm closing this tasks for now.
