### ISSUE TITLE
New Arrivals Slides on Home Page

### ISSUE THREAD

**Issue by rayhan** [Librarika/Issues#33]
Show a slides of new arrival items on the library home page. This lets other know whats new and whats going on with the library.

**Comment by alphauser7** [comment]
Hi,
This "new arrivals" slide is actually appearing on the PRIVATE library home page (when not logged in)! So ANY visitors who is not logged in can see titles of a PRIVATE library! Can you please correct this? Can you have it so it does NOT display for Private Libraries when user is not logged in. Otherwise its exposing the titles of the library to the public.

Thanks.
