### ISSUE TITLE
Delete Library Catalog

### ISSUE THREAD

**Issue by Liberryan** [Librarika/Issues#396]
I see that whole catalogs can be deleted upon request. I would like to ask you to delete the entire Digli catalog at digli.librarika.com.

I know that there must be protections so that whole catalogs don't end up trashed by accident, but since many libraries will want to test things before we know how much work it will take to undo on our own, is there any way to add a feature where we can do this (bulk delete/remove items and/or delete entire catalog) on our own?

I know this may not be ideal, but why not ask?

Also, I don't know if it is noted anywhere, but it may be good to explain somewhere that CSV catalog uploads will append rather than overwrite. If I am just doing it wrong, I would love to know!

**Comment by rayhan** [comment]
It is difficult to ensure authenticity of your request. Will you please submit the bulk delete request in our contact us (https://librarika.com/spages/contact) section from a registered email address, so that we can verify your ownership.

Yes, we will consider your suggestions about adding the options for librarians, we will also add the "upload will append not replace" message in FAQ page.

Thank you very much.

Regards
