### ISSUE TITLE
Possible new issue with barcode printing

### ISSUE THREAD

**Issue by timowen2** [Librarika/Issues#554]
In the last few days something has changed with barcode printing. This results in unreadable barcodes. Problem is either background changes to Chrome, Printer driver or Librarika. The fix is to insert a small left margin as the barcodes now being printed are cutting the first bar - I hope this doesn't affect too many people.

**Comment by Ugne-web** [comment]
I think I have simmilar issue...yesterday page seetings changed automatically on my librarika page. And now whenever I print barcode labels, barcode goes down. I tried to change seetings, but problem continues...I just need to make those labels to get on a very top of the sheet and then my problem is solved. But I tried to fix it entering different margins seetingas and it changed nothing. Maybe someone can help me?

**Comment by timowen2** [comment]
Hi

you first need to make sure you have the latest printer drivers installed on your computer.

After this you need to start with a set of Librarika settings and then change the settings for your printer - with luck you will be able to get things correct without changing Librarika settings.

I hope this helps

Tim

________________________________

**Comment by Ugne-web** [comment]
Yes I do have latest drivers. And everything worked fine until yesterday.
Now whenever I print barcode labels, this happens (I'm adding a photo). I
tried to change page seetings and it still didn't work. I don't know how to
fix it and get back to previous  seetings since I can't remember exact
numbers anymore.

We running a library and get visitors. And I hope we can solve this issue.
But at this moment I don't know how

2020-01-09, kt 13:40, timowen2 <notifications@github.com> rašė:

**Comment by Ugne-web** [comment]
2020-01-09, kt 13:52, Ugnė Jonaitytė <jugnyte@gmail.com> rašė:

**Comment by rasel2001** [comment]
@Ugne-web 

After checking your library we have seen that the Barcode Labels Page Settings was not correct. We have reset it to the default. Please check now and let us know if everything is okay.

**Comment by Ugne-web** [comment]
I'm really sorry, can you make them back to default again? Because I tried
to print and made so changes again in order to fix it. I tried again and
somehow first row of barcode labels starts not right from the top of the
sheet as it used to be.

Maybe issue is with our printer then?


2020-01-09, kt 16:25, rasel2001 <notifications@github.com> rašė:

**Comment by rasel2001** [comment]
@Ugne-web we have set the default settings for your library once again.

**Comment by Ugne-web** [comment]
Hello again. I`m facing same issues with barcode labels. We always used
labels with measurements 52,5x21,2 mm, A4 paper size and it worked fine
with librarika barcode labels seetings. But ever since January, somehow
those settings changed automatically and it didn`t fit with labels
measurements anyhow. I tried many times to change settings to find best
ones, but it didn`t help. I really do not know what to do. As about printer
drivers, they installed on my computer, newest version.

Is there any barcode label templates for such measurements (52,5 x 21,2 mm,
A4 paper size?


Thanks for any help.
