### ISSUE TITLE
BARCODE PRINTING SETTINGS HAVE CHANGED

### ISSUE THREAD

**Issue by timowen2** [Librarika/Issues#611]
I think you have made some changes which you need to roll back. save preferences is not working and barcode printing is now not working properly

**Comment by rasel2001** [comment]
**Save preferences is not working** 

The issue is occurred due to the Notified Librarians option in the Notifications / Reminders tab. The Notified Librarians field is required. Please fill up the Notified Librarians field then the preferences will be saved.

**Barcode printing is now not working properly**

Can you please share more details on barcode printing issue.

**Comment by timowen2** [comment]
I already had some thing in "Notified Librarians" - however I went in and put the cursor in the field and hit "Enter" - after this I could save preferences. 

To get barcode printing working again I had to go and change orientation back to "Landscape" and remove the entry for label height. I think these may get automatically reset if you change from roll to sheet (which I did to help out another user). My barcode printing is now OK.  Thankyou for your prompt attention to this, but can I ask that you issue some sort of notification when he system is enhanced or upgraded? This would help everyone so that we know what to expect - thanks, Tim
