### ISSUE TITLE
Member Barcode 

### ISSUE THREAD

**Issue by T-TeeJay-J** [Librarika/Issues#617]
After i painted a member barcode and scanned it on my mobile device, it automatically pasted it on the accession no. session instead of the member no. session
Is there any ways to solve this issue?

**Comment by jinia3636** [comment]
There is no way that it will take the accession number. Because member barcode is generated only with the member no. 

At the time of check-out, you need to choose the member no field and scan the member card (with attached barcode) then it will automatically fill the member no field. Then click on the submit button to commit the action.  

Also, please share us some screenshots of your issue so that we can look into this

**Comment by T-TeeJay-J** [comment]
![step 1](https://user-images.githubusercontent.com/51103742/74755785-9bce5800-52ae-11ea-9e02-fe3b77fc1200.jpg)
![step 2](https://user-images.githubusercontent.com/51103742/74755789-9cff8500-52ae-11ea-93b5-874e8063a40c.jpg)
![step 3](https://user-images.githubusercontent.com/51103742/74755792-9d981b80-52ae-11ea-9844-49d76db54606.jpg)

**Comment by jinia3636** [comment]
You can only scan the member no from our web version. In the case of mobile apps, you need to enter the Member No manually. 

Also, please enter the member no instead of member names while checking-out.

**Comment by T-TeeJay-J** [comment]
Is there any plan on further improve about the mobile version, because i find that there are quite a lot of bugs and very less function compare to the web version. In my library, my librarian are more approach into mobile application instead of the web version.

**Comment by jinia3636** [comment]
We have a plan to improve our mobile apps but we can not guarantee or provide a specific time-frame for this implementation. 

Please use our web version for now.
