### ISSUE TITLE
When processing imported .csv for catalog, I get the error "Error: An Internal Error Has Occurred."

### ISSUE THREAD

**Issue by anniecraycraft** [Librarika/Issues#657]
No details are provided with this error.

**Comment by jinia3636** [comment]
Maybe some characters were not encoded correctly in your CSV file. Please re-format your file using google docs.

Moreover, please split your files into multiple CSV files. We recommend a max of 500 records in each file for the best performance.    

If you further face any issue then please send us your CSV file so that we can look into this using our contact form https://librarika.com/spages/contact
