### ISSUE TITLE
Contractions don't work

### ISSUE THREAD

**Issue by OttTrLib** [Librarika/Issues#683]
My catalogue does not recognize contractions in the search function. If I type the title 'She's Not There' in the keyword search,  it will say 'No records found'. If I type 'Not There', it finds it. Same with other titles with contractions. "I'm Supposed to Relate to This' doesn't work. 'Relate to This' does. Any ideas?

**Comment by magnetar47** [comment]
I can confirm this issue. If I had to guess, the `'` character isn't being escaped properly.

**Comment by jinia3636** [comment]
We will check this issue and try to resolve it in the releases.

**Comment by magnetar47** [comment]
![screenshot](https://user-images.githubusercontent.com/88258122/149887764-513af08f-fb9b-472b-8f58-912738c565ea.png)

This seems to be related to the same issue of special characters not being escaped properly. This is the first time I'm seeing this happen, and it coincides with the first author name that contains double-quotes. Instead of displaying a red "Delete" button, it goes crazy and shows an entire paragraph, lol. :)

**Comment by jinia3636** [comment]
Please send your library URL via our contact us page https://librarika.com/spages/contact so that we can investigate the issue.

**Comment by jinia3636** [comment]
> My catalogue does not recognize contractions in the search function. If I type the title 'She's Not There' in the keyword search, it will say 'No records found'. If I type 'Not There', it finds it. Same with other titles with contractions. "I'm Supposed to Relate to This' doesn't work. 'Relate to This' does. Any ideas?

@OttTrLib 
For security issues, the contractions do not work in our Default search option. You need to choose other specific options like Title, Autors, Accession No, etc for searching with contractions.
