### ISSUE TITLE
Search Bar Not Recognising Books

### ISSUE THREAD

**Issue by asmeer97** [Librarika/Issues#703]
So I am trying to search for books in the Catalog, and when I scan the books, the books don't come up. Then I switch to smart add to add the books on, and it says, "The book is already in the Library" 

Any way around this?

**Comment by jinia3636** [comment]
The search option is working fine. After adding a new catalog item the search options works immediately except default search. It takes about a couple of hours to be functional for default search.

We have seen that there are Total 1058 titles and 1101 copies are available in your library catalogs.

If the search option is not still working for you please send us some screenshots so that we can help you to resolve the issue.
