### ISSUE TITLE
Recently added records not discoverable under default search

### ISSUE THREAD

**Issue by aravindakshan21** [Librarika/Issues#720]
This is similar to #710 
The search malfunction occurs when searching under Default while using a Category name or Tag.
The problem is only with records whose Category/Tag has been edited in the last two weeks or so. Previously edited records are appearing fine in the search.

The problem is there both in the admin and OPAC. We are at https://loab.librarika.com/

**Comment by rasel2001** [comment]
@aravindakshan21 

**Please note**: It may takes a couple of hours for the newly added catalog to reflect the search results for default search. Also, for OPAC only the records enabled for OPAC will be displayed on OPAC.

It often happens due to heavy traffic. If the default search is not working for the Default option then please select other options like ID, Title, ISBN, Call No, Tags, etc or **try sometimes later**.
