### ISSUE TITLE
Error Too Many Requests

### ISSUE THREAD

**Issue by jaimerogers** [Librarika/Issues#740]
When I have more than 5 people accessing the Librarika webpage for my school the website crashes, with a "too many requests" error code. It takes several minutes to get back online and will crash again when everyone's pages refresh. This is a MAJOR PROBLEM as it is not realistic to ensure that only a few students/staff use the catalogue at a time. Please solve this so that my school can access the catalogue and check out materials as intended.

**Comment by rasel2001** [comment]
For security protection, we have IP based ddos protection in place. 

That means, if there are too many requests generated from your ISPs public IP address, the system will temporarily block the requesting IP.

This may also be caused by malware or computer viruses simulating too many connections from your network?

Please [tell us](https://librarika.com/spages/contact) when and how  you face the issue and share your library name and public ip addresses your library will use, so that we can help you with the issue by looking into the traffic patterns and applying manual filters.

Hope this information was helpful.
