### ISSUE TITLE
Adding book photo

### ISSUE THREAD

**Issue by engagemindslearning** [Librarika/Issues#99]
I experience that for some books once the ISBN no is added the image of the book appears automatically in the right side of the screen. However, for a lot of other books with a valid ISBN the image does not appear. 
When I click on change photo nothing happens, basically I can't add a scanned image of a book. Can a manual add photo  be enabled?

**Comment by 2manybooks** [comment]
I've noticed that for some books, after the ISBN # has been entered with Smart Add the book cover photo load; in my case it may be because some of mine are old, perhaps out of print. I have found that I am able to upload a jpg file of the book cover; I simply do an online image search to find a picture of the book, download it to my desk top, then upload it into the catalog record.

**Comment by rayhan** [comment]
Seems its solved.

**Comment by Momobilette** [comment]
The issue is still there: recognise the ISBN but do not load the book image.
When I try to manually change the image, it will change it but will not save it: meaning when page is refreshed, the uploaded pictures disappears. please advise. thanks,
